### ISSUE TITLE
About detectCardType ?

### ISSUE THREAD

**Issue by franklt69** [ronald-hove/ion-custom-form-builder#1]
Hi Ronald, thanks for this excellent library, I have been playing with the credit card component, and I have not found a way to know what type of credit card the component detected, in the UI I can see the Visa icon, Mastercard, etc., but in the submit event submitForm (formData: any) {} formData has
card: "4111111111111111"
cardname: "Test"
cvv: "123"
expiry: "02/2021", is there any way to know the type of card detected in the submit event?

Regards,
Frank

**Comment by ronald-hove** [comment]
Hi Frank , Thanks for checkout out the library and  for submitting the first issue🥳🤓.

I have updated the library to take an option to return card type like so 

```html
  <ion-custom-form-builder
    [formFields]="fields"
    [submitButtonText]="'Pay Now'"
    [showIcons]="false"
    [showCardIcons]="false"
    (formSubmission)="submitForm($event)" 
    [returnCreditCardType]="true"
  >
  </ion-custom-form-builder>
```
by default it will not return it since that could be. breaking change so you have to give an input to return card type like so

**Comment by ronald-hove** [comment]
Closed issue as resolved
